export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const RESET_PASSWORD_RESPONSE = 'RESET_PASSWORD_RESPONSE';

export const GET_POSTS = 'GET_POSTS';
export const GET_POST = 'GET_POST';
export const CLEAR_POSTS = 'CLEAR_POSTS';

export const GET_USERS = 'GET_USERS';
export const GET_USER = 'GET_USER';

export const LOADING = 'LOADING';

export const CLEAR_USERS = 'CLEAR_USERS';
export const GET_SUGGESTIONS = 'GET_SUGGESTIONS';

export const GET_USER_CONVERSATION = 'GET_USER_CONVERSATION';
export const ADD_USER_TO_CHAT = 'ADD_USER_TO_CHAT';
export const REMOVE_USER_FROM_CHAT = 'REMOVE_USER_FROM_CHAT';
export const SENT_MESSAGE = 'SENT_MESSAGE';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';

